### ISSUE TITLE
Switch from frozendict to immutabledict.

### ISSUE THREAD

**Issue by crashvb** [matrix-org/python-canonicaljson#35]
**Is your feature request related to a problem? Please describe.**
Using pythong 3.8, importing canonicaljson requires frozendict, which is not being updated:

```log
.venv/lib/python3.8/site-packages/frozendict/__init__.py:16
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    class frozendict(collections.Mapping)
```

**Describe the solution you'd like**

Seems like this [PR](https://github.com/slezica/python-frozendict/issues/25) has a nice fix of switching over to [immuabledict](https://pypi.org/project/immutabledict/) instead.

**Describe alternatives you've considered**
Ignoring the warning, but if everybody gets in the habit of doing that we'd all be better off if there were no warnings in the first place ;)

**Additional context**
Really like the library, keep up the good work :)

**Comment by clokep** [comment]
Thanks, it seems that someone else has a fork too and will shortly have access to the PyPI version: https://github.com/Marco-Sulla/python-frozendict/releases

**Comment by ajs124** [comment]
>  Ignoring the warning […]

Seems like that stopped being an option with python 3.10:
```
test_canonicaljson (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_canonicaljson (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_canonicaljson
Traceback (most recent call last):
  File "/nix/store/vm2x0zimbpc15di391wgrkd3bdlfhfk1-python3-3.10.0a5/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/nix/store/vm2x0zimbpc15di391wgrkd3bdlfhfk1-python3-3.10.0a5/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/build/canonicaljson-1.4.0/test_canonicaljson.py", line 19, in <module>
    from canonicaljson import (
  File "/build/canonicaljson-1.4.0/canonicaljson.py", line 20, in <module>
    from frozendict import frozendict
  File "/nix/store/ayvada56aybvz7xqlbvjfi5fws0nimk2-python3.10-frozendict-1.2/lib/python3.10/site-packages/frozendict/__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

**Comment by clokep** [comment]
The owner of frozendict was just transferred on PyPI and they pushed a new version which should be compatible (2.0.2), so this *should* work now.

**Comment by richvdh** [comment]
the only reason we import `frozendict` is so that if an application uses it, we can serialize it correctly. Obviously, if we just replace the import with `immutabledict`, that will no longer work.

@clokep's suggestion of using the updated `frozendict` seems better

**Comment by richvdh** [comment]
in fact, it should just work? so we can close this?

**Comment by clokep** [comment]
> in fact, it should just work? so we can close this?

Yeah, it should just work. The PyPI package was transferred. I thought I hit close on this. 🤦

**Comment by crashvb** [comment]
Thanks all; I'll confirm out-of-band and open a new issue if, on the off chance, the warning still persists :)

**Comment by clokep** [comment]
Thanks @crashvb! No need for a new issue if you're still seeing it, you can just comment here. 👍
