### ISSUE TITLE
PyPI README doesn't match Github README

### ISSUE THREAD

**Issue by michellemounde** [matrix-org/python-canonicaljson#62]
The part of the docs stating that canonicaljson used simplejson is still in the PyPI docs. 

![Screenshot from 2023-11-02 18-15-33](https://github.com/matrix-org/python-canonicaljson/assets/84005549/49019642-d53d-4726-8a26-092940fa909f)

**Comment by DMRobertson** [comment]
Good spot. This is because we haven't made another release since https://github.com/matrix-org/python-canonicaljson/pull/61 which updated the readme.

**Comment by michellemounde** [comment]
Ooh, ok. So it will auto-update on the next release?

I am curious if there is another way to update PyPI because I was using the package then got a circular import error that's when I looked more closely at the method and saw that simplejson was chnaged to json.

**Comment by clokep** [comment]
> Ooh, ok. So it will auto-update on the next release?

Yes, although I don't think we have plans for this.

> I am curious if there is another way to update PyPI because I was using the package then got a circular import error

From our POV there's really no reason to use simplejson anymore, most of the performance improvements were upstreamed into Python itself. I'd recommend not using it.

**Comment by michellemounde** [comment]
After re-reading my comment I can see it was wrongly worded.

What I meant is I was trying to set canonicaljson to use json because on the PyPI page that is what is advised if you don't want to use simplejson. That's when I got a circular import error.

So I looked at the code that's when I found out that the underlying JSON implementation had been changed from simplejson to json.

In this issue I was asking if it is possible to edit the PyPI page to clarify that json is now used as default instead of simplejson before the next release. Or it has to wait until the next release?

**Comment by clokep** [comment]
> In this issue I was asking if it is possible to edit the PyPI page to clarify that json is now used as default instead of simplejson before the next release. Or it has to wait until the next release?

The PyPI pages are updated as part of releases (this is how PyPI works), so it is really asking for a new release. It doesn't really look like there are any pending changes except some README, unfortunately. (The tooling updates are good, but don't really affect releases.)

**Comment by michellemounde** [comment]
Aah, ok, thank you for the explanation.
